### ISSUE TITLE
Error using jupyter_nbextensions_configurator with nbclassic

### ISSUE THREAD

**Issue by scmmmh** [jupyter/nbclassic#140]
I'm trying to use nbclassic (0.4.2.) with the [jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) using the notebook_shim and getting the following error:

```
[I 2022-07-07 13:15:54.243 ServerApp] notebook_shim | extension was successfully loaded.
[D 2022-07-07 13:15:54.243 ServerApp] [jupyter_nbextensions_configurator] Loading 0.4.1
[D 2022-07-07 13:15:54.243 ServerApp] [jupyter_nbextensions_configurator]   Editing templates path to add /usr/local/lib/python3.9/site-packages/jupyter_nbextensions_configurator/templates
[D 2022-07-07 13:15:54.243 ServerApp] [jupyter_nbextensions_configurator]   Editing nbextensions path to add /usr/local/lib/python3.9/site-packages/jupyter_nbextensions_configurator/static
[D 2022-07-07 13:15:54.243 ServerApp] Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 351, in load_extension
        extension.load_all_points(self.serverapp)
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 231, in load_all_points
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 231, in <listcomp>
        return [self.load_point(point_name, serverapp) for point_name in self.extension_points]
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 224, in load_point
        return point.load(serverapp)
      File "/usr/local/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 150, in load
        return loader(serverapp)
      File "/usr/local/lib/python3.9/site-packages/jupyter_nbextensions_configurator/__init__.py", line 247, in load_jupyter_server_extension
        if static_files_path not in webapp.settings['nbextensions_path']:
    KeyError: 'nbextensions_path'
    
[W 2022-07-07 13:15:54.243 ServerApp] jupyter_nbextensions_configurator | extension failed loading with message: 'nbextensions_path'
```

I have also reported this here: https://github.com/jupyter/notebook_shim/issues/9, but I'm not sure which project it is best reported in.

**Comment by echarles** [comment]
Thx @scmmmh for reporting. I have the same issue and will look for a fix.

**Comment by echarles** [comment]
Just opened https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/141 to fix this.

**Comment by echarles** [comment]
https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/141 is waiting for reviews from the core maintainers. Please upvote that PR in the jupyter-contrib repository if you want to get this move forward.

**Comment by dleen** [comment]
Thanks @echarles !

That indeed fixes the stack trace. However when I apply the patch locally I am still seeing a bunch of 404s for the configurator:
```
[W 2022-11-02 19:59:16.514 ServerApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js
```
and the configurator doesn't actually load.

Any pointers where I might start debugging this?

For example:
```
jupyter nbclassic-extension list                                                   

Known nbextensions:
  config dir: /Users/dleen/.jupyter/nbconfig
    notebook section
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```

**Comment by echarles** [comment]
Thx for trying out @dleen and reporting here.

I have tested in a clean env and opened https://github.com/jupyter/nbclassic/pull/174/ to update the documentation. The following steps worked fine for me (the extension configuration is show and operational, no 404).

```bash
pip install nbclassic
pip install 'jupyter_nbextensions_configurator @ git+https://github.com/datalayer-externals/jupyter-notebook-configurator.git@fix/nbclassic#egg=jupyter_nbextensions_configurator'
jupyter nbclassic-extension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
jupyter nbclassic-extension enable --sys-prefix --py jupyter_nbextensions_configurator
jupyter nbclassic-serverextension enable --sys-prefix --py jupyter_nbextensions_configurator
jupyter nbclassic
```

<img width="1156" alt="Screenshot 2022-11-03 at 10 23 29" src="https://user-images.githubusercontent.com/226720/199686000-c9070fa6-cf8e-43a5-b2b9-532f41288064.png">

<img width="717" alt="Screenshot 2022-11-03 at 10 23 46" src="https://user-images.githubusercontent.com/226720/199686007-824b3a53-9a8b-4c81-aaa2-08f54cbb0051.png">

**Comment by echarles** [comment]
If I install and enable the last published `jupyter_nbextensions_configurator`and launch `jupyter notebook` (6.5.x), I get the following warning (the extension works fine).

```
[W 10:50:32.585 NotebookApp] [jupyter_nbextensions_configurator] nbextension 'nbextensions_configurator/config_menu/main' has duplicate listings in both '/Users/echarles/opt/miniconda3/envs/notebook/lib/python3.9/site-packages/jupyter_nbextensions_configurator/static/nbextensions_configurator/config_menu/config_menu.yaml' and '/Users/echarles/opt/miniconda3/envs/notebook/share/jupyter/nbextensions/nbextensions_configurator/config_menu/config_menu.yaml'
```

**Comment by echarles** [comment]
To add more info related to https://github.com/jupyter/nbclassic/issues/140#issuecomment-1301832643

After enabling with `jupyter nclassic-*` and launching with `jupyter nbclassic` or  `jupyter notebook` does not show any 404 and the extension is working fine on my env.

**Comment by echarles** [comment]
`jupyter_nbextensions_configurator` 0.6.1 has just been released and should fix this issue. Please test in you env and report if it works or not for you with the latest nbclassic and/or notebook 6. Thx.

**Comment by echarles** [comment]
If you test with nbclassic, please use the following commands before testing

```bash
jupyter nbclassic-extension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
jupyter nbclassic-extension enable --sys-prefix --py jupyter_nbextensions_configurator
jupyter serverextension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
jupyter serverextension enable --sys-prefix --py jupyter_nbextensions_configurator
```

For notebook:

```bash
jupyter nbextension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
jupyter nbextension enable --sys-prefix --py jupyter_nbextensions_configurator
jupyter serverextension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
jupyter serverextension enable --sys-prefix --py jupyter_nbextensions_configurator
```

**Comment by scmmmh** [comment]
I can confirm that this now works for me.

**Comment by echarles** [comment]
Thx. Closing as fixed.
