### ISSUE TITLE
500 Error at launch (KeyError: 'terminals_available' in self.settings)

### ISSUE THREAD

**Issue by defjaf** [jupyter/nbclassic#255]
Also [reported on discourse](https://discourse.jupyter.org/t/500-error-when-launching-nbclassic-terminals-available/20617).

macOS 13.5, Python 3.11.4 (homebrew)

With the recent move to notebook 7, I have been having issues with both `notebook` (documented [here](https://discourse.jupyter.org/t/notebook-7-issues-json-schema-nbclassic/20585) and [here](https://github.com/jupyter/notebook/issues/6974)) and `nbclassic`. 

For the latter, I am seeing a traceback, followed by a 500 error in the browser:
```
[E 2023-07-26 08:40:30.645 ServerApp] Uncaught exception GET /nbclassic/tree?token=e2a5e04ac6410a588e1132bac555b4f1fce1c781e1c9b4e0 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/nbclassic/tree?token=e2a5e04ac6410a588e1132bac555b4f1fce1c781e1c9b4e0', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/tornado/gen.py", line 786, in run
        yielded = self.gen.send(value)
                  ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.11/site-packages/nbclassic/tree/handlers.py", line 69, in get
        terminals_available=self.settings['terminals_available'],
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
    KeyError: 'terminals_available'
```

If I change "/opt/homebrew/lib/python3.11/site-packages/nbclassic/tree/handlers.py", line 69 from
```
                terminals_available=self.settings['terminals_available'],
```
to
```
                terminals_available=self.settings.get('terminals_available', False),
```
(as is done in `notebook/app.py`) it works (no errors, no 500), but I assume this shouldn't be necessary?

I assume it is a local config issue somehow, but in fact anything even if I get rid of all of the current directories listed with `jupyter --paths` it does not seem to help.

Any ideas?

**Comment by defjaf** [comment]
Partial fix: 

```
JUPYTER_PATH=/opt/homebrew/share/jupyter jupyter nbclassic
```
seems to fix it.

This appears to be a config problem in some interaction between how homebrew and jupyter set paths? 

(As such, I suspect that this is closely related to https://github.com/jupyter/notebook/issues/6974)

**Comment by jtpio** [comment]
cc @echarles @RRosio @ericsnekbytes for awareness

**Comment by defjaf** [comment]
See also https://github.com/jupyterlab/jupyterlab/issues/14890

**Comment by lp9052** [comment]
jupyter_server_terminals's latest update added the following to respect terminal setting:
```def initialize_settings(self) -> None:
        """Initialize settings."""
        if not self.serverapp.terminals_enabled:
            return
        self.initialize_configurables()
        self.settings.update(
            {"terminals_available": True, "terminal_manager": self.terminal_manager}
        )```
So if it is set to false then it is guaranteed to fail the nbclassic/tree.
the latest code will fix this. Will we have a release soon?
