### ISSUE TITLE
Error Enabling jupyter_nbextensions_configurator with Jupyter Notebook

### ISSUE THREAD

**Issue by palparam** [jupyter/nbclassic#276]
I am using Python 3.12.3.
I installed nbextension and configurator by the commands:
$pip install jupyter_contrib_nbextensions
$pip install jupyter_nbextensions_configurator

Then when I try to enable configurator,
$jupyter contrib nbextension install --user

hitting error :
Traceback (most recent call last):
File "", line 198, in run_module_as_main
File "", line 88, in run_code
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Scripts\jupyter-contrib.EXE_main.py", line 7, in
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
super().launch_instance(argv=argv, **kwargs)
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\config\application.py", line 1073, in launch_instance
app = cls.instance(**kwargs)
^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\traitlets\config\configurable.py", line 583, in instance
inst = cls(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_contrib_core\application.py", line 27, in init
self.refresh_subcommands()
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_contrib_core\application.py", line 43, in refresh_subcommands
get_subcommands_dict = entrypoint.load()
^^^^^^^^^^^^^^^^^
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources_init.py", line 2482, in load
return self.resolve()
^^^^^^^^^^^^^^
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources_init.py", line 2488, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_contrib_nbextensions_init.py", line 5, in
import jupyter_nbextensions_configurator
File "C:\Users\pps\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_nbextensions_configurator_init_.py", line 18, in
from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'

$jupyter --version
Selected Jupyter core packages...
IPython : 8.24.0
ipykernel : 6.29.4
ipywidgets : not installed
jupyter_client : 8.6.1
jupyter_core : 5.7.2
jupyter_server : 2.14.0
jupyterlab : 4.1.8
nbclient : 0.10.0
nbconvert : 7.16.4
nbformat : 5.10.4
notebook : 7.1.3
qtconsole : not installed
traitlets : 5.14.3

I installed 'nbclassic' package also as mentioned in other thread as solution for jupyterlab but still seeing issue
Ref: https://github.com/jupyterlab/jupyterlab/issues/15053

I also reported to JupyterLab, they directed me reach here.
https://github.com/jupyterlab/jupyterlab/issues/16281

**Comment by krassowski** [comment]
> notebook : 7.1.3

so briefly, `jupyter_nbextensions_configurator` is not itself compatible with notebook v7. There has been a PR to make it not error out https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/166 which was merged by @RRosio but it looks like a new version was not released.

In short the extension system is just very different in Notebook v7.

**Comment by krassowski** [comment]
Maybe with https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/166 it could work with nbclassic?
